### ISSUE TITLE
nginx 504 Gateway Time-out

### ISSUE THREAD

**Issue by eeveeta** [GoogleCloudPlatform/gke-jupyter-classroom#3]
I'm following the instructions outlined here: https://cloud.google.com/solutions/using-tensorflow-jupyterhub-classrooms. I'm in the final step of going to the .xip.io url, but I get an nginx time-out error. I'm ignoring the certificate warning just like the tutorial says. 

I can see the containers being created as well as the filer vm on the GCE dashboard. I cannot see any error in their serial console outputs.

**Comment by bVTiger** [comment]
I had same error. 
In nginx log was: 
[error] 13#13: *1276 upstream timed out (110: Connection timed out) while connecting to upstream, client: x.x.x.x, server: , request: "GET / HTTP/1.1", upstream: "http://y.y.y.y:8000/", host: "jhub.y.y.y.y.xip.io"
In jupyterhub pod log was:
"Unable to mount volumes for pod "jupyterhub-4173372450-0m9v2_jupyterhub(e10bd93d-6491-11e7-a69b-42010af00150)": timeout expired waiting for volumes to attach/mount for pod "jupyterhub"/"jupyterhub-4173372450-0m9v2". list of unattached/unmounted volumes=[nfs]
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "jupyterhub"/"jupyterhub-4173372450-0m9v2". list of unattached/unmounted volumes=[nfs]"

During created file server I used my own names for server parameters. I recreated it with names, given in doc (deployment name, instance name and storage name)

And it worked

**Comment by davidraleigh** [comment]
@eeveeta , one of the things that @bVTiger made me aware of was that I was using the `EXTERNAL_IP` address for my nfs server instead of the `INTERNAL_IP`. That solved it for me. Thanks @bVTiger!

**Comment by stanifrolov** [comment]
@bVTiger what do you mean with _instance name_, I just used the prefilled name "fileserver" as the docs do not mention a change in _instance name_? One thing I noticed is that the compute instance name became "jupyterhub-filer-vm" although I set the deployment name to "jupyterhub-filer".

The only difference is I am using a different zone. Do you think this could be the issue? However, I used a different compute zone through out the complete instructions.

**Comment by sveesible** [comment]
Different zone shouldn't matter. Configuration on the NFS Server has been fixed, it was previously not mounting the disk and exporting it if the names of the disk were changed during config.  You can also use the computer name of the file server instead of IP address.  The name is going to match what you see in the cloud console, which I believe the Launcher adds a "-vm" to the end of the name, so what you enter is not what you get unfortunately.

**Comment by stanifrolov** [comment]
@sveesible thanks!
